name: site_blog_develop_ci_cd

on:
  push:
    branches:
      - develop

jobs:
  lint_and_testing:
    runs-on: ubuntu-latest
    environment:
      name: "development"
    steps:
      - uses: actions/checkout@v2
      - name: ⌛️ Installing dependencies
        run: yarn install

      - name: 👀 Linting
        run: yarn run lint

      - name: 🌡 Testing
        run: yarn run test:ci
        env:
          GATSBY_SITE_URL: ${{ secrets.GATSBY_SITE_URL }}
          SENDGRID_APIKEY: ${{ secrets.GATSBY_SENDGRID_APIKEY }}

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: lint_and_testing
    environment:
      name: "development"
    steps:
      - uses: actions/checkout@v1

      - name: ⌛️ Installing dependencies
        run: yarn install

      - name: 🏗 Building
        run: yarn run build
        env:
          GATSBY_SITE_URL: ${{ secrets.GATSBY_SITE_URL }}
          SENDGRID_APIKEY: ${{ secrets.GATSBY_SENDGRID_APIKEY }}

      - name: 📦 Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './public'
          production-branch: develop
          production-deploy: true
          github-token: ${{ secrets.BLOG_GITHUB_TOKEN }}
          deploy-message: "Deployed from GitHub Actions"
          enable-pull-request-comment: false
          github-deployment-environment: "development"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1

